### ISSUE TITLE
Node Package Management

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/labs-engineering-standards#11]
* Do we standardize on NPM or Yarn or just leave this open?
* Do we standardize on whether or not to check in lock files? Shrinkwrap?https://docs.npmjs.com/cli/shrinkwrap.html

**Comment by tinomen** [comment]
**Yarn**
I've yet to successfully have a project (or team) be completely on Yarn. npm seems unescapable. 

That said I'd love to try to make yarn the required mgr.

**Comment by tinomen** [comment]
I'm cloudy on the lock files. Isn't it best to commit them but they end up being noise in PRs?

**Comment by berniedurfee** [comment]
> I've yet to successfully have a project (or team) be completely on Yarn. npm seems inescapable.

@tinomen I agree, I think NPM and Yarn ought to be allowed, but that's it.

As for lock files, I'm a fan of committing them because it _should_ help developer environments to be more consistent. It'll likely cause merge issues on occasion, but I think having consistent modules across environments is more important.

It's also recommended by NPM: https://docs.npmjs.com/files/package-lock.json

So I think we require lock files to be committed.
