### ISSUE TITLE
Need a standard for deleting old code

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/labs-engineering-standards#14]
Many developers comment out unused code. This is a bad habit and is rarely needed. We should create a standard that "When code is no longer needed, it gets deleted".

**Comment by tinomen** [comment]
Do we make an entry under Quality?

**Comment by berniedurfee** [comment]
> Do we make an entry under Quality?

Yep, you want to submit a PR?

**Comment by tinomen** [comment]
DOH! Forgot to reference the issue from the PR/commit
