### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/labs-engineering-standards#16]
Should we allow the use of Firebase?

There are many alternatives in AWS. I think do not think we should permit Firebase, thoughts?

**Comment by rholdy** [comment]
No. We should require a real, deployed, backend and data store,

**Comment by jessmartin** [comment]
Agreed. The one case that I've seen where students choose Firebase was based on Android and how easy Firebase makes auth for Android apps. We shouldn't have that reason any more. 🤷‍♂ 

A really nice engineering standard doc could focus on the "standard stack" including specifying a standard backend. So in addition to saying "no" to Firebase, we could point to the engineering "standard stack" doc.

**Comment by tinomen** [comment]
The other potential reason is to have FE and BE working from live events without setting up a MQ.

Otherwise +1

**Comment by jessmartin** [comment]
> The other potential reason is to have FE and BE working from live events without setting up a MQ.

This actually brings up a question I've had for a while: what do we recommend as an MQ in Labs?

**Comment by tinomen** [comment]
I've only used rabbitMQ the past 6 years but I know there are now pubsub _toys_ available that do point to point quite well. SNS/SQS is not an valid replacement and I'm ready to fight about that one. 👊 😆

**Comment by tinomen** [comment]
Closing since we've published this.
