### ISSUE TITLE
Should MongoDB be allowed as data persistence

### ISSUE THREAD

**Issue by tinomen** [Lambda-School-Labs/labs-engineering-standards#23]
MongoDB is of interest to the students but they don't have instruction on it. Many have the misconception that it is very flexible, when in reality key/value stores are the least flexible but incredibly efficient. That efficiency requires an understanding of the problem and good data modeling. This is where I get concerned with the ability of the team and time on staff to support it.

**Comment by berniedurfee** [comment]
I certainly don't want students (or anyone who for that matter) to have to deploy and manage Mongo on servers.

If anything, we can approve DocumentDB (which is a managed AWS flavor of MongoDB): https://aws.amazon.com/blogs/aws/new-amazon-documentdb-with-mongodb-compatibility-fast-scalable-and-highly-available/

Is this the Heroku equivalent? https://devcenter.heroku.com/articles/mongolab

I think it's probably okay to approve these managed versions of Mongo, but probably should require Engineering Manager approval to vet the use case.

**Comment by tinomen** [comment]
Yes, heroku has some providers that manage mongo. 

I feel like we require the review of the data model as well. My limited experience with mongodb out of Lambda is that the flexibility stiffens up after a few deploys if the schema changes too much or that the code becomes stinky with exceptions on where the data is. (doc versions and what not)

**Comment by tinomen** [comment]
@jessmartin @ryan-hamblin can we close this with a `NOT NOW`?

**Comment by berniedurfee** [comment]
I'm good with that. Most asks for NoSQL tend to have a rationale of 'just because'. There haven't been any projects so far that seemed like a good fit for anything other than a bog standard Postgres DB.

**Comment by thirdeyeclub** [comment]
Since no one was taught it it might jsut slow down dev time for the students, if they can pull it off I dont't see why not

**Comment by berniedurfee** [comment]
> Since no one was taught it it might just slow down dev time for the students, if they can pull it off I don't see why not

Thanks for the input! This is a very salient point and one that will drive many of these decisions.

This decision (and any other decision in this document) is only temporary. These decisions will be adjusted, changed and rewritten many times as the landscape of relevant technology and our ability to effectively support those technologies changes.

That a team _can_ use MongoDB doesn't mean they _should_. So far, I've not seen any compelling cases for using anything except Postgres to store data. I think there are certainly many compelling cases for non-relational databases, but nothing I've seen so far has hit that mark.

If a team _does_ present a case for using MongoDB or any other non-relational DB, we'll have that discussion and will then add that to the standards with some guidance as to exactly when and how to decide between Postgres and another technology.

In any event, Engineering Managers will be discussing this soon and will come back with a decision.

Thanks again!

**Comment by tinomen** [comment]
+1 to not allow it.
