### ISSUE TITLE
Clarification: SC-300 vs TH-120 Contradiction re: Auth0

### ISSUE THREAD

**Issue by DomBruno** [Lambda-School-Labs/labs-engineering-standards#33]
Questions raised as to whether SC-300 or TH-120 take precedence as they appear to be in contradiction to many students.

SC-300 states "(SC-300) Permitted IdP List
Only IdPs in the following list shall be used by a Labs project:

https://www.okta.com/
https://auth0.com/"

while TH-120 states "(TH-120) Identity Providers
The only permitted identity providers for Lambda School Labs projects are listed below:
Okta
All others are prohibited from use."

In the event they are not contradictory and the confusion is based on a lack of understanding (the standards for example, may apply to different environments) it might behoove us to clarify.

Thank you for all the efforts you are putting into building the standards, hopefully by communicating the hurdles we have implementing them, we can create a robust, polished set of reasonable and comprehensive standards.

**Comment by berniedurfee** [comment]
@DomBruno Thank you!

I submitted a PR that needs review, but for now only Okta should be used for new projects. Auth0 should not be used.
