### ISSUE TITLE
Clarification: NJ-100 Should this include npx

### ISSUE THREAD

**Issue by mrzacsmith** [Lambda-School-Labs/labs-engineering-standards#36]
NJ-100 Use Only Approved Package Managers
Only the following Node.js package managers are approved for projects in Labs:
NPM
-Version > 6.0.0
 --Yarn
-Version > 2.0.0
--Preferred

Should the current language standard include npx > 6.0.0 be included as Approved Package Manager. Although npx is an npm package, it is required for some packages, ie create-react-app. CRA is no longer available with npm.

**Comment by berniedurfee** [comment]
Thanks for the feedback! But, unless I'm mistaken, `npx` is actually a component of the `npm` package manager that makes executing NPM scripts. I think it is actually part of the NPM system. So, it's really just part of NPM, not a standalone package manager itself. Am I reading that right?

**Comment by tinomen** [comment]
NPX is not a package manager, it merely eXecutes scripts/binaries found in the installed npm packages.
