### ISSUE TITLE
Need standard for enabling branch protection

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/labs-engineering-standards#42]
Should require master branch to always be protected and require reviews and checks

**Comment by jessmartin** [comment]
Agreed. For reviewers, I think 2 reviewers should suffice. 

And needs to pass all checks, like ya said. CodeClimate coverage and maintainability. Passing test suite.

**Comment by tinomen** [comment]
You mean like this

https://lambda-school-labs.github.io/labs-engineering-standards/topics/github/#gh-311-require-pull-request-reviews-before-merging

I'll make it more specific "to master" 😛

**Comment by berniedurfee** [comment]
I thought there was something there already. Probably need to use more GitHub specific language and point to a how-to document in Notion with steps to set it up.

**Comment by tinomen** [comment]
It's currently pointing to the step by step guide on github. It's part of a bigger topic so we could add other links as well.

**Comment by berniedurfee** [comment]
Let's finalize this using a specific GitHub setup:

* Branch protection rule for _master_ branch:
  * Required approving reviews: 2

* Require status checks to pass before merging
  * Require branches to be up to date before merging

We'll need to specifically designate some status checked, let's leave this open for right now and just get it in place to ensure 2 reviews. We'll can discuss the status checks individually.

**Comment by berniedurfee** [comment]
Closed by #48
