### ISSUE TITLE
Standardize on Jest for testing Node.js REST APIs

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/labs-engineering-standards#66]
There are _many_ different frameworks and tools for testing Node.js REST API code.

- Jest is really popular, well supported and comes all-in-one with mocking and various assertion functions.
- Jest is very well documented and has a large supporting community.
- Jest provides all of the features and functionality we need for testing Node.js REST APIs
- There is an eslint plugin for Jest that provides some style checking

I'm proposing a new item that specifically restricts testing of Node.js REST APIs to using Jest, which would include various plugins and ancillary tools like Supertest, etc.

**Comment by ryan-hamblin** [comment]
100% on board with Jest. 

It can also combine with React Testing Library (by and large the accepted standard) on the front end as well for component testing. 

Some mix of React Testing Lib + Jest is my vote!

**Comment by jgmuchiri** [comment]
This proposal gets my vote!

**Comment by berniedurfee** [comment]
Need a review for #67
