### ISSUE TITLE
Can we set Code Climate to Ignore .SVG files

### ISSUE THREAD

**Issue by derekjpeters** [Lambda-School-Labs/labs-engineering-standards#70]
Is there a standard for the type of image files?  Code Climate is capturing .SVG files as issues and it makes it difficult for build ons.

**Comment by berniedurfee** [comment]
Per the docs: https://docs.codeclimate.com/docs/excluding-files-and-folders

"Furthermore, engines only run their analysis on files with an appropriate file extension for the language being analyzed (.rb for a Ruby engine, .py for a Python engine, etc). Therefore, in most cases you should not need to specify excludes for files in languages other than your target languages."

Which repo specifically is having this issue?

**Comment by berniedurfee** [comment]
@derekjpeters ⬆️

**Comment by berniedurfee** [comment]
This should be good now, reopen if there are any more issue. Thanks!
