### ISSUE TITLE
Can we make it clear that Passport.js != Identity Providers/Managers (like Okta)

### ISSUE THREAD

**Issue by LeTanque** [Lambda-School-Labs/labs-engineering-standards#72]
There has been a lot of confusion with teams about Oauth/SSO. Most students read the engineering standards and think that the only way they can build "sign in with Google" is by integrating Okta. 

However, teams can roll their own solution entirely or use a library like passport.js.

**Comment by berniedurfee** [comment]
It's actually correct, per the current standards, to say that "the only way to use 'Google' for SSO is by integrating through Okta'. That's actually the intent.

Yes, you can use passport.js to use Google authentication directly, but this is not permitted per the current standards.

For non-SPAs, you would use this http://www.passportjs.org/packages/passport-okta-oauth/ and not this http://www.passportjs.org/packages/passport-google-oauth/.

The objective being that students learn to use a more robust platform for managing identities, which is what Okta provides.

For an SPA, you could handle the authentication in the browser and send JWTs with API calls to authenticate to the backend API: https://developer.okta.com/docs/guides/sign-into-spa/angular/before-you-begin/

Okta supports Google as an IdP, so if you want to add authentication using Google, it's easy to configure that in Okta.

**Comment by LeTanque** [comment]
Oh wow, that's interesting! I guess I should reframe the engineering standards as engineering hints, in my mind, lol. 

So teams can use the passport strategy for Okta so that Okta can get in on the data, but not deal with the intended SSO directly.  And only for non-SPA. 

Seems like we're really pushing for Okta!

> For an SPA, you could handle the authentication in the browser and send JWTs with API calls to authenticate to the backend API: https://developer.okta.com/docs/guides/sign-into-spa/angular/before-you-begin/

I think you meant to post the react docs.

> Okta supports Google as an IdP, so if you want to add authentication using Google, it's easy to configure that in Okta.

Easy to configure Google SSO is passport.js. Setting up Okta is kinda like building an F1 car for a gokart track. 

----------------

I thought Labs was an opportunity for young devs to work on an agile team and build something noteworthy. A chance to grow. 

Then I thought we were moving towards a standard so that we could better support teams as they grow. That seemed like a really good idea. 

I also thought, after the whole Next.js thing, that the focus of Labs was not necessarily to learn a whole new stack, but to build or build-on to something with mostly what they know. 

The problem: Okta is not very well supported in PT and teams are spending an inordinate amount of time learning something that feels overbuilt for what they are trying to accomplish. 

The standards are starting to feel arbitrary and the ambiguity of it all, and refusal to clarify the actual docs, feels almost... malicious is too strong, but that's what I keep thinking. 
 
Anyways, I'll stop making issues and stop trying to clarify things in the standards.

**Comment by berniedurfee** [comment]
@LeTanque please don't stop creating issues! :) You've spurred some great internal discussion.

In fact, we have started an initiative to create guides for the technologies included in the standards. These will help clarify the specific usage of each of the technologies.

We also discussed Okta and will likely be changing our standards around identity providers.

We are also constantly discussing whether the boundaries that we set are properly balancing between our need to maintain and scale the program with our desire to allow students the opportunity to learn how to build using the best tools and building blocks in the industry.

The program is alway in flux to try to match the rate of change in the industry. These standards will always be in flux as a result. Your (and everyone's) input and feedback is very influential and does help guide and inform us. Thank you!
