### ISSUE TITLE
Heroku does not provide nameservers by default

### ISSUE THREAD

**Issue by LeTanque** [Lambda-School-Labs/labs-engineering-standards#73]
But there is a third party add-on that teams can use that will provide nameservers and allow teams to use custom domains. I wrote up a short notion guide for your approval:

https://www.notion.so/PointDNS-process-a7cb59a3343e4c3695ff6be656664123

**Comment by berniedurfee** [comment]
Awesome, thank you! I've added a slightly modified version of your doc to the student handbook.

https://www.notion.so/lambdaschool/Heroku-075bd2c947264834b6fc954eeaf0ff94

**Comment by berniedurfee** [comment]
I'm going to add a new item for supported 3rd party DNS providers.
