### ISSUE TITLE
Add Swift to allowed languages list

### ISSUE THREAD

**Issue by israelgonzalezb** [Lambda-School-Labs/labs-engineering-standards#82]
iOS engineering students at Lambda use Swift. The alternative, Objective C, is a prohibited language in Labs. Unless there is a reason for its absence, we should add Swift to the table of approved languages.

**Comment by JimmyMcBride** [comment]
I think the standards are particularly tailored for web students. I don't think they hold iOS students accountable to that standard. I could be wrong.

**Comment by berniedurfee** [comment]
@israelgonzalezb would you mind submitting a PR to add Swift?

@JimmyMcBride no :) this was just a total oversight on our part. These are engineering standards, so they'll cover web, iOS, Android, DS, etc. they should be inclusive of _any_ software engineering happening in Labs.

**Comment by JimmyMcBride** [comment]
Oh, nice! Cool deal. Good catch Izzy! :fire:

**Comment by berniedurfee** [comment]
Closed by #91
