### ISSUE TITLE
Increase the "Lines of Code" limit from 25 -> 50

### ISSUE THREAD

**Issue by ryan-hamblin** [Lambda-School-Labs/labs-engineering-standards#86]
Most 'code smells' I'm seeing on front end repos have to do with the function size limit set at 25. While 50 seems like a larger number it is very common to see components reach well over 25 lines of code due to the fact that React components return 'markup'. While lines of code is a good way to look at a codebase and measure its maintainability in terms of 'readability', I vote we increase the limit to allow students to focus on actual code smells in their repos.

**Comment by berniedurfee** [comment]
I think 50 is reasonable
