### ISSUE TITLE
Disable similar code check?

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/labs-engineering-standards#87]
Given the nature of the boilerplate style frameworks we use, this check seems to throw false positives almost exclusively.

What say you we disable this check and focus on other issues?

**Comment by ryan-hamblin** [comment]
This is similar to increasing the lines of code allotted per function and some of the problems iOS students are having with the reporter as well. 

See #86

**Comment by JustThisAlex** [comment]
One of those iOS-issues ist the following:
In our [project](https://codeclimate.com/github/Lambda-School-Labs/community-calendar-ios/issues), we have an issue regarding auto-generated files. We'd need the ability to somehow ignore these files and snippets, that point to those files from grading. In this case, the API.swift file is autogenerated, so the issues regarding that, and the first issue in the Event.swift can only be resolved by changing that file, which we're unable to do.

Also, the cognitive complexity rating is all over the place in swift, so disabling that, or setting it to a value >20 is necessary.

**Comment by berniedurfee** [comment]
> One of those iOS-issues ist the following:
> In our [project](https://codeclimate.com/github/Lambda-School-Labs/community-calendar-ios/issues), we have an issue regarding auto-generated files. We'd need the ability to somehow ignore these files and snippets, that point to those files, from grading. In this case, the API.swift file is autogenerated, so the issues regarding that, and the first issue in the Event.swift can only be resolved by changing that file, which we're unable to do.

I added a note in the exceptions to include generated code.


> Also, the cognitive complexity rating is all over the place in swift, so disabling that, or setting it to a value >20 is necessary.

Can you point me at some code where this is an issue?

**Comment by JustThisAlex** [comment]
So, how would I remove a file from the codeclimate scoring?

[Here](https://imgur.com/xgKCOEH) is an example.
